-- SCRIPT to clean out DocFactory processing data from LIVE and HISTORICAL tables.

-- Documaker Assembly Line schema name.
TRUNCATE TABLE PUBS; COMMIT;
TRUNCATE TABLE BCHS_RCPS; COMMIT;
TRUNCATE TABLE RCPS; COMMIT;
TRUNCATE TABLE BCHS; COMMIT;
TRUNCATE TABLE TRNS; COMMIT;
TRUNCATE TABLE TRNSD; COMMIT;
TRUNCATE TABLE JOBS; COMMIT;

TRUNCATE TABLE PUBSHIST;COMMIT;
TRUNCATE TABLE BCHS_RCPSHIST; COMMIT;
TRUNCATE TABLE RCPSHIST;COMMIT;
TRUNCATE TABLE BCHSHIST;COMMIT;
TRUNCATE TABLE TRNSHIST;COMMIT;
TRUNCATE TABLE JOBSHIST;COMMIT;

TRUNCATE TABLE LOGS; COMMIT;
TRUNCATE TABLE TRNSLOG; COMMIT;
TRUNCATE TABLE ERRS; COMMIT;

EXIT;

ALTER TABLE JOBS ENABLE ROW MOVEMENT;
ALTER TABLE JOBS SHRINK SPACE CASCADE;
ALTER TABLE TRNSD ENABLE ROW MOVEMENT;
ALTER TABLE TRNSD SHRINK SPACE CASCADE;
ALTER TABLE TRNS ENABLE ROW MOVEMENT;
-- Note this doesn't work currently because of a function-based index on the table.
--ALTER TABLE TRNS SHRINK SPACE CASCADE;
ALTER TABLE RCPS ENABLE ROW MOVEMENT;
ALTER TABLE RCPS SHRINK SPACE CASCADE;
ALTER TABLE BCHS ENABLE ROW MOVEMENT;
ALTER TABLE BCHS SHRINK SPACE CASCADE;
ALTER TABLE BCHS_RCPS ENABLE ROW MOVEMENT;
ALTER TABLE BCHS_RCPS SHRINK SPACE CASCADE;
ALTER TABLE PUBS ENABLE ROW MOVEMENT;
ALTER TABLE PUBS SHRINK SPACE CASCADE;

ALTER TABLE JOBSHIST ENABLE ROW MOVEMENT;
ALTER TABLE JOBSHIST SHRINK SPACE CASCADE;
ALTER TABLE TRNSHIST ENABLE ROW MOVEMENT;
ALTER TABLE TRNSHIST SHRINK SPACE CASCADE;
ALTER TABLE RCPSHIST ENABLE ROW MOVEMENT;
ALTER TABLE RCPSHIST SHRINK SPACE CASCADE;
ALTER TABLE BCHS_RCPSHIST ENABLE ROW MOVEMENT;
ALTER TABLE BCHS_RCPSHIST SHRINK SPACE CASCADE;
ALTER TABLE BCHSHIST ENABLE ROW MOVEMENT;
ALTER TABLE BCHSHIST SHRINK SPACE CASCADE;
ALTER TABLE PUBSHIST ENABLE ROW MOVEMENT;
ALTER TABLE PUBSHIST SHRINK SPACE CASCADE;
ALTER TABLE LOGS ENABLE ROW MOVEMENT;
ALTER TABLE LOGS SHRINK SPACE CASCADE;
ALTER TABLE TRNSLOG ENABLE ROW MOVEMENT;
-- Note this doesn't work currently because of a function-based index on the table.
-- ALTER TABLE TRNSLOG SHRINK SPACE CASCADE;
ALTER TABLE ERRS ENABLE ROW MOVEMENT;
ALTER TABLE ERRS SHRINK SPACE CASCADE;

COMMIT;
exit;
