package oracle.dws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

@WebService(wsdlLocation="http://192.168.1.72:7001/DWSV0AL1/CompositionService?WSDL",
  targetNamespace="oracle/documaker/schema/ws/composition", name="CompositionServicePortType")
@XmlSeeAlso(
  { oracle.dws.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface CompositionServicePortType
{
  @WebMethod(action="doCallIDS")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="doCallIDS", fault =
      { @FaultAction(value="oracle/documaker/schema/ws/composition/CompositionServicePortType/doCallIDS/Fault/CompositionFault",
          className=oracle.dws.CompositionFault.class) }, output="oracle/documaker/schema/ws/composition/CompositionServicePortType/doCallIDSResponse")
  @WebResult(targetNamespace="oracle/documaker/schema/ws/composition",
    partName="DoCallIDSResponse", name="DoCallIDSResponse")
  public oracle.dws.types.DoCallIDSResponse doCallIDS(@WebParam(targetNamespace="oracle/documaker/schema/ws/composition",
      partName="DoCallIDSRequest", name="DoCallIDSRequest")
    oracle.dws.types.DoCallIDSRequest DoCallIDSRequest)
    throws oracle.dws.CompositionFault;

  @WebMethod(action="doCallIDSOneWay")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="doCallIDSOneWay")
  @Oneway
  public void doCallIDSOneWay(@WebParam(targetNamespace="oracle/documaker/schema/ws/composition",
      partName="DoCallIDSOneWayRequest", name="DoCallIDSOneWayRequest")
    oracle.dws.types.DoCallIDSOneWayRequest DoCallIDSOneWayRequest);
}
