package oracle.dws;

import javax.xml.ws.WebFault;

@WebFault(faultBean="oracle.dws.types.CompositionFault", targetNamespace="oracle/documaker/schema/ws/composition",
  name="CompositionFault")
public class CompositionFault
  extends Exception
{
  private oracle.dws.types.CompositionFault faultInfo;

  public CompositionFault(String message,
                          oracle.dws.types.CompositionFault faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public CompositionFault(String message,
                          oracle.dws.types.CompositionFault faultInfo,
                          Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

    CompositionFault(String p0) {
        return;
    }

    public oracle.dws.types.CompositionFault getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(oracle.dws.types.CompositionFault faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)
