package oracle.dws;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

@WebServiceClient(wsdlLocation="http://192.168.1.72:7001/DWSV0AL1/CompositionService?WSDL",
  targetNamespace="oracle/documaker/schema/ws/composition", name="CompositionService")
public class CompositionService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("oracle.dws.CompositionService");
      URL baseUrl = CompositionService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            CompositionService.class.getResource("http://192.168.1.72:7001/DWSV0AL1/CompositionService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://192.168.1.72:7001/DWSV0AL1/CompositionService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://192.168.1.72:7001/DWSV0AL1/CompositionService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://192.168.1.72:7001/DWSV0AL1/CompositionService?WSDL",
          e);
    }
  }

  public CompositionService()
  {
    super(wsdlLocationURL,
          new QName("oracle/documaker/schema/ws/composition",
                    "CompositionService"));
  }

  public CompositionService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="CompositionServicePort")
  public oracle.dws.CompositionServicePortType getCompositionServicePort()
  {
    return (oracle.dws.CompositionServicePortType) super.getPort(new QName("oracle/documaker/schema/ws/composition",
                                                                           "CompositionServicePort"),
                                                                 oracle.dws.CompositionServicePortType.class);
  }

  @WebEndpoint(name="CompositionServicePort")
  public oracle.dws.CompositionServicePortType getCompositionServicePort(WebServiceFeature... features)
  {
    return (oracle.dws.CompositionServicePortType) super.getPort(new QName("oracle/documaker/schema/ws/composition",
                                                                           "CompositionServicePort"),
                                                                 oracle.dws.CompositionServicePortType.class,
                                                                 features);
  }
}
